set1 = set()
set1.add(8)
set1.add(9)
set1.add((6,7))
print("Set after Addition of Three elements: ",set1)
set1.update([10, 11])
print("Set after Addition of elements using Update: ",set1)
set1.remove(8)
print("Set after Removal of elements: ",set1)
set1.discard(9)
print("Set after Discarding two elements: ",set1)
set1.pop()
print("Set after popping an element: ",set1)
set1.clear()
print("Set after clearing all the elements: ",set1)